#ifndef MP_CACHE_INTERNAL_CONFIG_CONSTANTS_H
#define MP_CACHE_INTERNAL_CONFIG_CONSTANTS_H

/*
 * Central source of truth for durable mp-cache constants.
 * Add service defaults, config keys, stable protocol strings, limits, capacities,
 * and environment variable names here instead of scattering literals across modules.
 */

/* Shared text and path capacities. */
#define MP_CACHE_TEXT_CAP 128u
#define MP_CACHE_NAME_CAP 64u
#define MP_CACHE_SECRET_REF_CAP 256u
#define MP_CACHE_PATH_CAP 4096u
#define MP_CACHE_LINE_CAPACITY 2048u

/* Compiled bootstrap defaults. */
#define MP_CACHE_DEFAULT_CONFIG_PATH "configs/bootstrap.yaml"
#define MP_CACHE_DEFAULT_SERVICE_NAME "mp-cache"
#define MP_CACHE_DEFAULT_ENVIRONMENT_NAME "local"
#define MP_CACHE_DEFAULT_BUILD_VERSION "0.0.0"
#define MP_CACHE_DEFAULT_SOCKET_PATH ".tmp/run/mp-cache.sock"
#define MP_CACHE_DEFAULT_PID_FILE_PATH ".tmp/run/mp-cache.pid"
#define MP_CACHE_DEFAULT_DATA_DIRECTORY ".tmp/data"
#define MP_CACHE_DEFAULT_EXPORT_DIRECTORY ".tmp/exports"
#define MP_CACHE_DEFAULT_CHECKPOINT_PATH ".tmp/data/state.checkpoint"
#define MP_CACHE_DEFAULT_JOURNAL_PATH ".tmp/data/state.journal"
#define MP_CACHE_DEFAULT_LOG_DIRECTORY "logging"
#define MP_CACHE_DEFAULT_BOOTSTRAP_ADMIN_TOKEN_SECRET_REF "env:MP_SECRET_LOCAL_BOOTSTRAP_ADMIN_TOKEN"
#define MP_CACHE_DEFAULT_STORAGE_KEY_SECRET_REF "env:MP_SECRET_LOCAL_STORAGE_KEY"
#define MP_CACHE_DEFAULT_MEMORY_LIMIT_BYTES (256ull * 1024ull * 1024ull)
#define MP_CACHE_DEFAULT_TTL_SECONDS 172800u
#define MP_CACHE_DEFAULT_MIN_TTL_SECONDS 1u
#define MP_CACHE_DEFAULT_MAX_TTL_SECONDS 2592000u
#define MP_CACHE_DEFAULT_MAX_KEY_BYTES 256u
#define MP_CACHE_DEFAULT_MAX_VALUE_BYTES (1024u * 1024u)
#define MP_CACHE_DEFAULT_BUCKET_COUNT 4096u
#define MP_CACHE_DEFAULT_MAX_EXPORT_FILES 16u
#define MP_CACHE_DEFAULT_SHUTDOWN_TIMEOUT_MILLIS 5000u
#define MP_CACHE_DEFAULT_SWEEP_INTERVAL_SECONDS 5u
#define MP_CACHE_DEFAULT_MAX_LOG_LINES 200u
#define MP_CACHE_DEFAULT_RATE_LIMIT_REQUESTS 240u
#define MP_CACHE_DEFAULT_RATE_LIMIT_WINDOW_SECONDS 60u

/* Config sections and keys accepted by the bootstrap YAML parser. */
#define MP_CACHE_CONFIG_SECTION_SERVICE "service"
#define MP_CACHE_CONFIG_SECTION_SERVER "server"
#define MP_CACHE_CONFIG_SECTION_CACHE "cache"
#define MP_CACHE_CONFIG_SECTION_STORAGE "storage"
#define MP_CACHE_CONFIG_SECTION_OBSERVABILITY "observability"
#define MP_CACHE_CONFIG_SECTION_MP_LOGGER "mp_logger"
#define MP_CACHE_CONFIG_SECTION_SECURITY "security"
#define MP_CACHE_CONFIG_KEY_ENVIRONMENT_NAME "environment_name"
#define MP_CACHE_CONFIG_KEY_SERVICE_NAME "service_name"
#define MP_CACHE_CONFIG_KEY_BUILD_VERSION "build_version"
#define MP_CACHE_CONFIG_KEY_SOCKET_PATH "socket_path"
#define MP_CACHE_CONFIG_KEY_PID_FILE_PATH "pid_file_path"
#define MP_CACHE_CONFIG_KEY_SHUTDOWN_TIMEOUT_MILLIS "shutdown_timeout_millis"
#define MP_CACHE_CONFIG_KEY_MEMORY_LIMIT_BYTES "memory_limit_bytes"
#define MP_CACHE_CONFIG_KEY_DEFAULT_TTL_SECONDS "default_ttl_seconds"
#define MP_CACHE_CONFIG_KEY_MIN_TTL_SECONDS "min_ttl_seconds"
#define MP_CACHE_CONFIG_KEY_MAX_TTL_SECONDS "max_ttl_seconds"
#define MP_CACHE_CONFIG_KEY_MAX_KEY_BYTES "max_key_bytes"
#define MP_CACHE_CONFIG_KEY_MAX_VALUE_BYTES "max_value_bytes"
#define MP_CACHE_CONFIG_KEY_BUCKET_COUNT "bucket_count"
#define MP_CACHE_CONFIG_KEY_SWEEP_INTERVAL_SECONDS "sweep_interval_seconds"
#define MP_CACHE_CONFIG_KEY_DATA_DIRECTORY "data_directory"
#define MP_CACHE_CONFIG_KEY_EXPORT_DIRECTORY "export_directory"
#define MP_CACHE_CONFIG_KEY_CHECKPOINT_PATH "checkpoint_path"
#define MP_CACHE_CONFIG_KEY_JOURNAL_PATH "journal_path"
#define MP_CACHE_CONFIG_KEY_MAX_EXPORT_FILES "max_export_files"
#define MP_CACHE_CONFIG_KEY_LOG_DIRECTORY "log_directory"
#define MP_CACHE_CONFIG_KEY_MAX_LOG_LINES "max_log_lines"
#define MP_CACHE_CONFIG_KEY_LOGGER_BOOTSTRAP_PATH "bootstrap_path"
#define MP_CACHE_CONFIG_KEY_LOGGER_BUFFER_CAPACITY "buffer_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_MESSAGE_CAPACITY "message_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_CONTEXT_CAPACITY "context_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_FIELD_CAPACITY "field_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_FIELD_KEY_CAPACITY "field_key_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_FIELD_VALUE_CAPACITY "field_value_capacity"
#define MP_CACHE_CONFIG_KEY_LOGGER_FORMAT "format"
#define MP_CACHE_CONFIG_KEY_LOGGER_PRETTY_OUTPUT "pretty_output"
#define MP_CACHE_CONFIG_KEY_LOGGER_FILE_NAME_PREFIX "file_name_prefix"
#define MP_CACHE_CONFIG_KEY_LOGGER_BACKUP_FILE_NAME_PREFIX "backup_file_name_prefix"
#define MP_CACHE_CONFIG_KEY_LOGGER_ACTIVE_STREAMS "active_streams"
#define MP_CACHE_CONFIG_KEY_LOGGER_STDOUT_MIN_LEVEL "stdout_min_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_STDOUT_MAX_LEVEL "stdout_max_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_STDERR_MIN_LEVEL "stderr_min_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_STDERR_MAX_LEVEL "stderr_max_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_FILE_MIN_LEVEL "file_min_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_FILE_MAX_LEVEL "file_max_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_UDP_MIN_LEVEL "udp_min_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_UDP_MAX_LEVEL "udp_max_level"
#define MP_CACHE_CONFIG_KEY_LOGGER_UDP_HOST "udp_host"
#define MP_CACHE_CONFIG_KEY_LOGGER_UDP_PORT "udp_port"
#define MP_CACHE_CONFIG_KEY_BOOTSTRAP_ADMIN_TOKEN_SECRET_REF "bootstrap_admin_token_secret_ref"
#define MP_CACHE_CONFIG_KEY_STORAGE_KEY_SECRET_REF "storage_key_secret_ref"
#define MP_CACHE_CONFIG_KEY_RATE_LIMIT_REQUESTS "rate_limit_requests"
#define MP_CACHE_CONFIG_KEY_RATE_LIMIT_WINDOW_SECONDS "rate_limit_window_seconds"

/* Environment variables and secret reference schemes. */
#define MP_CACHE_ENV_SOCKET_PATH "MP_SOCKET_PATH"
#define MP_CACHE_ENV_TOKEN "MP_CACHE_TOKEN"
#define MP_CACHE_SECRET_ENV_PREFIX "env:"
#define MP_CACHE_SECRET_ENV_PREFIX_LENGTH 4u
#define MP_CACHE_SECRET_FILE_PREFIX "file:"
#define MP_CACHE_SECRET_FILE_PREFIX_LENGTH 5u

/* Security and token limits. */
#define MP_CACHE_SHA256_SIZE 32u
#define MP_CACHE_SHA256_BLOCK_SIZE 64u
#define MP_CACHE_NONCE_SIZE 16u
#define MP_CACHE_CLIENT_ID_CAP 64u
#define MP_CACHE_TOKEN_HASH_SIZE 32u
#define MP_CACHE_TOKEN_TEXT_CAP ((MP_CACHE_TOKEN_HASH_SIZE * 2u) + 1u)
#define MP_CACHE_TOKEN_RANDOM_BYTES MP_CACHE_TOKEN_HASH_SIZE
#define MP_CACHE_BOOTSTRAP_ADMIN_ID "bootstrap-admin"
#define MP_CACHE_MAX_CLIENTS 1024u
#define MP_CACHE_INITIAL_CLIENT_CAPACITY 8u
#define MP_CACHE_ROLE_NAME_CLIENT "client"
#define MP_CACHE_ROLE_NAME_OPERATOR "operator"
#define MP_CACHE_ROLE_NAME_ADMIN "admin"
#define MP_CACHE_ROLE_NAME_NONE "none"

/* Local HTTP parser, API response, and control CLI constants. */
#define MP_CACHE_HTTP_REQUEST_CAPACITY 65536u
#define MP_CACHE_HTTP_HEADER_CAPACITY 2048u
#define MP_CACHE_HTTP_PATH_CAPACITY 512u
#define MP_CACHE_HTTP_BODY_CAPACITY 32768u
#define MP_CACHE_HTTP_JSON_ARRAY_LIMIT 256u
#define MP_CACHE_HTTP_METHOD_CAPACITY 16u
#define MP_CACHE_HTTP_AUTHORIZATION_CAPACITY 256u
#define MP_CACHE_HTTP_CONTENT_TYPE_JSON "application/json"
#define MP_CACHE_HTTP_EMPTY_JSON_OBJECT "{}"
#define MP_CACHE_JSON_ESCAPE_EXPANSION 6u
#define MP_CACHE_CONTROL_CLI_REQUEST_BODY_CAPACITY 4096u
#define MP_CACHE_HTTP_ERROR_CODE_CONFLICT "conflict"
#define MP_CACHE_HTTP_ERROR_CODE_FORBIDDEN "forbidden"
#define MP_CACHE_HTTP_ERROR_CODE_INTERNAL_ERROR "internal_error"
#define MP_CACHE_HTTP_ERROR_CODE_INVALID_ARGUMENT "invalid_argument"
#define MP_CACHE_HTTP_ERROR_CODE_LIMIT_EXCEEDED "limit_exceeded"
#define MP_CACHE_HTTP_ERROR_CODE_NOT_FOUND "not_found"
#define MP_CACHE_HTTP_ERROR_CODE_UNAUTHORIZED "unauthorized"

/* Stable HTTP route paths, prefixes, suffixes, and formatting templates. */
#define MP_CACHE_HTTP_ROUTE_ROOT "/"
#define MP_CACHE_HTTP_ROUTE_LEGACY_HEALTH "/health"
#define MP_CACHE_HTTP_ROUTE_HEALTH "/v1/health"
#define MP_CACHE_HTTP_ROUTE_CACHE_PREFIX "/v1/cache/"
#define MP_CACHE_HTTP_ROUTE_CACHE_FORMAT "/v1/cache/%s"
#define MP_CACHE_HTTP_ROUTE_STATS "/v1/stats"
#define MP_CACHE_HTTP_ROUTE_MEMORY_METRICS "/v1/metrics/memory"
#define MP_CACHE_HTTP_ROUTE_UPTIME "/v1/uptime"
#define MP_CACHE_HTTP_ROUTE_LOGS "/v1/logs"
#define MP_CACHE_HTTP_ROUTE_LOGS_TAIL_FORMAT "/v1/logs?tail=%s"
#define MP_CACHE_HTTP_ROUTE_CLIENTS "/v1/clients"
#define MP_CACHE_HTTP_ROUTE_CLIENTS_PREFIX "/v1/clients/"
#define MP_CACHE_HTTP_ROUTE_CLIENT_ROTATE_SUFFIX "/rotate-token"
#define MP_CACHE_HTTP_ROUTE_CLIENT_INVALIDATE_SUFFIX "/invalidate-token"
#define MP_CACHE_HTTP_ROUTE_CLIENT_ROTATE_FORMAT "/v1/clients/%s/rotate-token"
#define MP_CACHE_HTTP_ROUTE_CLIENT_INVALIDATE_FORMAT "/v1/clients/%s/invalidate-token"
#define MP_CACHE_HTTP_ROUTE_EXPORT "/v1/export"
#define MP_CACHE_HTTP_ROUTE_IMPORT "/v1/import"
#define MP_CACHE_HTTP_ROUTE_PURGE_KEYS "/v1/purge/keys"
#define MP_CACHE_HTTP_ROUTE_PURGE_ALL "/v1/purge/all"
#define MP_CACHE_HTTP_ROUTE_HELP_MESSAGE "use " MP_CACHE_HTTP_ROUTE_LEGACY_HEALTH " or /v1/* endpoints"

/* Stable diagnostic status names returned by module status-name helpers. */
#define MP_CACHE_STATUS_NAME_OK "OK"
#define MP_CACHE_STATUS_NAME_NOT_FOUND "NOT_FOUND"
#define MP_CACHE_STATUS_NAME_CONFLICT "CONFLICT"
#define MP_CACHE_STATUS_NAME_EXPIRED "EXPIRED"
#define MP_CACHE_STATUS_NAME_INVALID_ARGUMENT "INVALID_ARGUMENT"
#define MP_CACHE_STATUS_NAME_LIMIT_EXCEEDED "LIMIT_EXCEEDED"
#define MP_CACHE_STATUS_NAME_NO_MEMORY "NO_MEMORY"
#define MP_CACHE_STATUS_NAME_IO_ERROR "IO_ERROR"
#define MP_CACHE_STATUS_NAME_PARSE_ERROR "PARSE_ERROR"
#define MP_CACHE_STATUS_NAME_SECRET_ERROR "SECRET_ERROR"
#define MP_CACHE_STATUS_NAME_UNAUTHORIZED "UNAUTHORIZED"
#define MP_CACHE_STATUS_NAME_VALIDATION_ERROR "VALIDATION_ERROR"
#define MP_CACHE_STATUS_NAME_UNKNOWN "UNKNOWN"

/* Storage packet and export constants. */
#define MP_CACHE_STORAGE_STATE_MAGIC "MPCSTAT1"
#define MP_CACHE_STORAGE_JOURNAL_MAGIC "MPCJNL1"
#define MP_CACHE_STORAGE_EXPORT_MAGIC "MPCEXPT1"
#define MP_CACHE_STORAGE_PACKET_HEADER_SIZE 64u
#define MP_CACHE_STORAGE_HEADER_MAC_OFFSET 32u
#define MP_CACHE_STORAGE_STATE_VERSION 2u
#define MP_CACHE_STORAGE_JOURNAL_VERSION 2u
#define MP_CACHE_STORAGE_BUFFER_INITIAL_CAPACITY 256u
#define MP_CACHE_STORAGE_MAX_PACKET_OVERHEAD_BYTES (16u * 1024u * 1024u)
#define MP_CACHE_STORAGE_EXPORT_FILE_PREFIX "mp-cache-export-"
#define MP_CACHE_STORAGE_EXPORT_FILE_PREFIX_LENGTH 16u
#define MP_CACHE_STORAGE_EXPORT_FILE_NAME_FORMAT "%s/mp-cache-export-%ld-%ld.bin"
#define MP_CACHE_STORAGE_JOURNAL_OP_SET_VALUE 1u
#define MP_CACHE_STORAGE_JOURNAL_OP_DELETE_VALUE 2u
#define MP_CACHE_STORAGE_JOURNAL_OP_CLIENT_UPSERT_VALUE 3u
#define MP_CACHE_STORAGE_JOURNAL_OP_PURGE_ALL_VALUE 4u

/* Logging defaults used when bootstrapping native/mp_logger. */
#define MP_CACHE_LOG_MESSAGE_CAPACITY 1024u
#define MP_CACHE_LOG_CONTEXT_CAPACITY 512u
#define MP_CACHE_LOG_TAIL_READ_CAPACITY (1024u * 1024u)
#define MP_CACHE_LOGGER_BUFFER_CAPACITY 4096u
#define MP_CACHE_LOGGER_MESSAGE_CAPACITY 1024u
#define MP_CACHE_LOGGER_CONTEXT_CAPACITY 512u
#define MP_CACHE_LOGGER_FIELD_CAPACITY 8u
#define MP_CACHE_LOGGER_FIELD_KEY_CAPACITY 32u
#define MP_CACHE_LOGGER_FIELD_VALUE_CAPACITY 128u
#define MP_CACHE_LOGGER_FORMAT "json"
#define MP_CACHE_LOGGER_PRETTY_OUTPUT 0
#define MP_CACHE_LOGGER_FILE_NAME_PREFIX "mp-cache"
#define MP_CACHE_LOGGER_BACKUP_FILE_NAME_PREFIX "mp-cache-internal"
#define MP_CACHE_LOGGER_ACTIVE_STREAMS "stdout,stderr,file"
#define MP_CACHE_LOGGER_STDOUT_MIN_LEVEL "trace"
#define MP_CACHE_LOGGER_STDOUT_MAX_LEVEL "info"
#define MP_CACHE_LOGGER_STDERR_MIN_LEVEL "warning"
#define MP_CACHE_LOGGER_STDERR_MAX_LEVEL "fatal"
#define MP_CACHE_LOGGER_FILE_MIN_LEVEL "trace"
#define MP_CACHE_LOGGER_FILE_MAX_LEVEL "fatal"
#define MP_CACHE_LOGGER_UDP_MIN_LEVEL "error"
#define MP_CACHE_LOGGER_UDP_MAX_LEVEL "fatal"
#define MP_CACHE_LOGGER_UDP_HOST "127.0.0.1"
#define MP_CACHE_LOGGER_UDP_PORT 5514u
#define MP_CACHE_LOGGER_BOOTSTRAP_PATH "native/mp_logger/configs/logger.bootstrap.yaml"

#endif
